export enum NotificationType {
  // Post related
  POST_REPORTED = "POST_REPORTED",
  POST_ARCHIVED = "POST_ARCHIVED",
  POST_APPROVED = "POST_APPROVED",
  POST_LIKED = "POST_LIKED",
  POST_COMMENTED = "POST_COMMENTED",
  
  // User related
  NEW_FOLLOWER = "NEW_FOLLOWER",
  MENTIONED_IN_COMMENT = "MENTIONED_IN_COMMENT",
  MENTIONED_IN_POST = "MENTIONED_IN_POST",
  
  // System related
  SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT",
  ACCOUNT_WARNING = "ACCOUNT_WARNING"
} 